/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedStaffRouteImport } from './routes/_authed.staff'
import { Route as AuthedScheduleRouteImport } from './routes/_authed.schedule'
import { Route as AuthedPatientsRouteImport } from './routes/_authed.patients'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedAppointmentsRouteImport } from './routes/_authed.appointments'
import { Route as AuthedPatientsIndexRouteImport } from './routes/_authed.patients.index'
import { Route as AuthedPatientsNewRouteImport } from './routes/_authed.patients.new'
import { Route as AuthedPatientsIdRouteImport } from './routes/_authed.patients.$id'
import { Route as AuthedPatientsIdIndexRouteImport } from './routes/_authed.patients.$id.index'
import { Route as AuthedPatientsIdCardRouteImport } from './routes/_authed.patients.$id.card'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedStaffRoute = AuthedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPatientsRoute = AuthedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppointmentsRoute = AuthedAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPatientsIndexRoute = AuthedPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPatientsRoute,
} as any)
const AuthedPatientsNewRoute = AuthedPatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedPatientsRoute,
} as any)
const AuthedPatientsIdRoute = AuthedPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedPatientsRoute,
} as any)
const AuthedPatientsIdIndexRoute = AuthedPatientsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPatientsIdRoute,
} as any)
const AuthedPatientsIdCardRoute = AuthedPatientsIdCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AuthedPatientsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/appointments': typeof AuthedAppointmentsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/patients': typeof AuthedPatientsRouteWithChildren
  '/schedule': typeof AuthedScheduleRoute
  '/staff': typeof AuthedStaffRoute
  '/patients/$id': typeof AuthedPatientsIdRouteWithChildren
  '/patients/new': typeof AuthedPatientsNewRoute
  '/patients/': typeof AuthedPatientsIndexRoute
  '/patients/$id/card': typeof AuthedPatientsIdCardRoute
  '/patients/$id/': typeof AuthedPatientsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/appointments': typeof AuthedAppointmentsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/schedule': typeof AuthedScheduleRoute
  '/staff': typeof AuthedStaffRoute
  '/patients/new': typeof AuthedPatientsNewRoute
  '/patients': typeof AuthedPatientsIndexRoute
  '/patients/$id/card': typeof AuthedPatientsIdCardRoute
  '/patients/$id': typeof AuthedPatientsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/appointments': typeof AuthedAppointmentsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/patients': typeof AuthedPatientsRouteWithChildren
  '/_authed/schedule': typeof AuthedScheduleRoute
  '/_authed/staff': typeof AuthedStaffRoute
  '/_authed/patients/$id': typeof AuthedPatientsIdRouteWithChildren
  '/_authed/patients/new': typeof AuthedPatientsNewRoute
  '/_authed/patients/': typeof AuthedPatientsIndexRoute
  '/_authed/patients/$id/card': typeof AuthedPatientsIdCardRoute
  '/_authed/patients/$id/': typeof AuthedPatientsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/appointments'
    | '/dashboard'
    | '/patients'
    | '/schedule'
    | '/staff'
    | '/patients/$id'
    | '/patients/new'
    | '/patients/'
    | '/patients/$id/card'
    | '/patients/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/appointments'
    | '/dashboard'
    | '/schedule'
    | '/staff'
    | '/patients/new'
    | '/patients'
    | '/patients/$id/card'
    | '/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/appointments'
    | '/_authed/dashboard'
    | '/_authed/patients'
    | '/_authed/schedule'
    | '/_authed/staff'
    | '/_authed/patients/$id'
    | '/_authed/patients/new'
    | '/_authed/patients/'
    | '/_authed/patients/$id/card'
    | '/_authed/patients/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/staff': {
      id: '/_authed/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthedStaffRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/patients': {
      id: '/_authed/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthedPatientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/appointments': {
      id: '/_authed/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthedAppointmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/patients/': {
      id: '/_authed/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthedPatientsIndexRouteImport
      parentRoute: typeof AuthedPatientsRoute
    }
    '/_authed/patients/new': {
      id: '/_authed/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthedPatientsNewRouteImport
      parentRoute: typeof AuthedPatientsRoute
    }
    '/_authed/patients/$id': {
      id: '/_authed/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthedPatientsIdRouteImport
      parentRoute: typeof AuthedPatientsRoute
    }
    '/_authed/patients/$id/': {
      id: '/_authed/patients/$id/'
      path: '/'
      fullPath: '/patients/$id/'
      preLoaderRoute: typeof AuthedPatientsIdIndexRouteImport
      parentRoute: typeof AuthedPatientsIdRoute
    }
    '/_authed/patients/$id/card': {
      id: '/_authed/patients/$id/card'
      path: '/card'
      fullPath: '/patients/$id/card'
      preLoaderRoute: typeof AuthedPatientsIdCardRouteImport
      parentRoute: typeof AuthedPatientsIdRoute
    }
  }
}

interface AuthedPatientsIdRouteChildren {
  AuthedPatientsIdCardRoute: typeof AuthedPatientsIdCardRoute
  AuthedPatientsIdIndexRoute: typeof AuthedPatientsIdIndexRoute
}

const AuthedPatientsIdRouteChildren: AuthedPatientsIdRouteChildren = {
  AuthedPatientsIdCardRoute: AuthedPatientsIdCardRoute,
  AuthedPatientsIdIndexRoute: AuthedPatientsIdIndexRoute,
}

const AuthedPatientsIdRouteWithChildren =
  AuthedPatientsIdRoute._addFileChildren(AuthedPatientsIdRouteChildren)

interface AuthedPatientsRouteChildren {
  AuthedPatientsIdRoute: typeof AuthedPatientsIdRouteWithChildren
  AuthedPatientsNewRoute: typeof AuthedPatientsNewRoute
  AuthedPatientsIndexRoute: typeof AuthedPatientsIndexRoute
}

const AuthedPatientsRouteChildren: AuthedPatientsRouteChildren = {
  AuthedPatientsIdRoute: AuthedPatientsIdRouteWithChildren,
  AuthedPatientsNewRoute: AuthedPatientsNewRoute,
  AuthedPatientsIndexRoute: AuthedPatientsIndexRoute,
}

const AuthedPatientsRouteWithChildren = AuthedPatientsRoute._addFileChildren(
  AuthedPatientsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppointmentsRoute: typeof AuthedAppointmentsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedPatientsRoute: typeof AuthedPatientsRouteWithChildren
  AuthedScheduleRoute: typeof AuthedScheduleRoute
  AuthedStaffRoute: typeof AuthedStaffRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppointmentsRoute: AuthedAppointmentsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedPatientsRoute: AuthedPatientsRouteWithChildren,
  AuthedScheduleRoute: AuthedScheduleRoute,
  AuthedStaffRoute: AuthedStaffRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
